name: Code Review with GPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # GitHub 레포지토리의 코드를 체크아웃합니다.

      - name: Run code review with OpenAI GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # OpenAI API 키를 환경 변수로 설정합니다.
        run: |
          # Pull Request에서 변경된 파일 중 확장자가 .js, .py, .java, .ts인 파일만 필터링
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.(js|py|java|ts)$')

          # 변경된 파일 리스트를 확인하고, 비어 있으면 종료
          echo "Changed files: $FILES"
          if [ -z "$FILES" ]; then
            echo "No eligible files found for review."
            exit 0
          fi

          # 각 파일에 대해 OpenAI API를 호출하여 코드 리뷰 수행
          for file in $FILES; do
            echo "Processing file: $file"  # 현재 파일명 확인
            CONTENT=$(cat $file)  # 파일 내용 읽기
            
            # GPT 모델에 리뷰 요청
            RESPONSE=$(curl -s -X POST https://api.openai.com/v1/completions \
                       -H "Content-Type: application/json" \
                       -H "Authorization: Bearer $OPENAI_API_KEY" \
                       -d "{
                             \"model\": \"text-davinci-003\",
                             \"prompt\": \"Please review the following code:\n\n$CONTENT\n\nProvide suggestions for improvement.\",
                             \"temperature\": 0.5,
                             \"max_tokens\": 200
                           }")
            echo "Review for $file: $RESPONSE" >> review_output.txt  # 결과를 review_output.txt 파일에 저장
          done

      - name: Post review comment
        uses: peter-evans/create-or-update-comment@v2 # PR에 GPT 리뷰 결과를 댓글로 추가하는 액션
        with:
          issue-number: ${{ github.event.pull_request.number }} # PR 번호를 참조하여 해당 PR에 댓글을 추가
          body: |
            ### Automated Code Review by GPT
            $(cat review_output.txt)  # review_output.txt 파일의 내용을 PR 댓글에 표시
